/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the version of the CORINT Decision Engine */
export declare function version(): string
/** Decision Engine wrapper for Node.js */
export declare class Engine {
  /**
   * Create a new Decision Engine instance from repository path
   *
   * # Arguments
   * * `repository_path` - Path to the rule repository directory
   */
  static fromRepository(repositoryPath: string): Promise<Engine>
  /**
   * Create a new Decision Engine instance with rule content
   *
   * # Arguments
   * * `pipeline_id` - Identifier for the pipeline
   * * `yaml_content` - YAML content of the pipeline
   */
  static fromYaml(pipelineId: string, yamlContent: string): Promise<Engine>
  /**
   * Execute a decision request
   *
   * # Arguments
   * * `request_json` - Decision request as JSON string
   *
   * # Returns
   * Decision response as JSON string
   */
  decide(requestJson: string): Promise<string>
  /**
   * Execute a simple decision with event data only
   *
   * # Arguments
   * * `event_data_json` - Event data as JSON string
   *
   * # Returns
   * Decision response as JSON string
   */
  decideSimple(eventDataJson: string): Promise<string>
}
