version: "0.1"

---

pipeline:
  id: test_simple
  name: Simple Test
  entry: check

  when:
    all:
      - event.amount > 0

  steps:
    - step:
        id: check
        name: Amount Check
        type: rule_inline
        rule:
          when:
            all:
              - event.amount > 100
          outcomes:
            - high_amount
          actions:
            - type: flag
              reason: "High amount"
