version: "0.1"

# ============================================================================
# COMPREHENSIVE DSL DEMONSTRATION
# ============================================================================
# This file demonstrates core DSL features in a single integrated example
# Features demonstrated:
#   - Basic rule conditions with logical operators (AND, OR)
#   - Comparison operators (>, <, ==, !=, >=, <=)
#   - String operations (in, contains)
#   - Arithmetic expressions
#   - Nested logical groups (any, all)
#   - Negative scoring
#   - Ruleset composition
#   - Decision logic with multiple outcomes
#   - Conditional branching in pipelines
# ============================================================================

# ----------------------------------------------------------------------------
# Rule 1: High Value Transaction Detection
# ----------------------------------------------------------------------------

rule:
  id: high_value_transaction
  name: High Value Transaction Detection
  description: Detect transactions with unusually high amounts

  when:
    all:
      - event.transaction.amount > 10000
      - event.transaction.currency == "USD"

  score: 75

  metadata:
    category: transaction_monitoring
    severity: high
    tags: [high_value, aml]
    rule_version: "1.0.0"

# ----------------------------------------------------------------------------
# Rule 2: Suspicious User Behavior (OR logic)
# ----------------------------------------------------------------------------

rule:
  id: suspicious_user_behavior
  name: Suspicious User Behavior Pattern
  description: Detect various suspicious behaviors using OR logic

  when:
    any: 
      - event.user.login_attempts > 5
      - event.user.session_duration < 60
      - event.user.ip_country != event.user.registered_country

  score: 60

  metadata:
    category: user_behavior
    severity: medium
    tags: [behavior, suspicious]

# ----------------------------------------------------------------------------
# Rule 3: Confirmed Fraud Pattern (AND logic)
# ----------------------------------------------------------------------------
---

rule:
  id: confirmed_fraud_pattern
  name: Confirmed Fraud Pattern
  description: Multiple indicators must all be present

  when:
    all:
      - all:
          - event.transaction.amount > 5000
          - event.user.account_age_days < 7
          - event.transaction.recipient_new == true

  score: 95

  metadata:
    category: fraud
    severity: critical
    tags: [fraud, high_confidence]

# ----------------------------------------------------------------------------
# Rule 4: Complex Fraud Detection (Nested logic)
# ----------------------------------------------------------------------------

rule:
  id: complex_fraud_detection
  name: Complex Fraud Detection Logic
  description: Nested AND/OR conditions

  when:
    all:
      - event.transaction.amount > 1000
      - any:
          - all:
              - event.user.vip_status == false
              - event.transaction.international == true
          - all:
              - event.user.verified == false
              - event.transaction.payment_method == "crypto"

  score: 80

  metadata:
    category: fraud
    severity: high
    tags: [fraud, complex_pattern]

# ----------------------------------------------------------------------------
# Rule 5: Risk Threshold Check (Comparison operators)
# ----------------------------------------------------------------------------
---

rule:
  id: risk_threshold_check
  name: Risk Threshold Validation
  description: Various comparison operators

  when:
    all:
      - event.risk_score >= 70
      - event.risk_score <= 90
      - event.confidence_level != "low"
      - event.transaction.count < 100

  score: 65

  metadata:
    category: risk_management
    severity: medium

# ----------------------------------------------------------------------------
# Rule 6: Payment Method Check (String operations)
# ----------------------------------------------------------------------------

rule:
  id: payment_method_check
  name: Restricted Payment Method Detection
  description: Check for restricted payment methods

  when:
    any:
      - event.transaction.payment_method in ["crypto", "gift_card", "money_order"]
      - event.transaction.description contains "urgent"

  score: 70

  metadata:
    category: payment_fraud
    severity: high
    tags: [payment, restricted_method]

# ----------------------------------------------------------------------------
# Rule 7: Velocity Check (Arithmetic in conditions)
# ----------------------------------------------------------------------------

rule:
  id: velocity_check
  name: Transaction Velocity Check
  description: Arithmetic operations in conditions

  when:
    all:
      # Transaction amount is more than 3x user's average
      - event.transaction.amount > event.user.average_transaction * 3
      # Transaction count is more than 2x user's daily average
      - event.transaction.count_24h > event.user.avg_daily_count * 2

  score: 55

  metadata:
    category: velocity
    severity: medium

# ----------------------------------------------------------------------------
# Rule 8: Trusted User Bonus (Negative scoring)
# ----------------------------------------------------------------------------

rule:
  id: trusted_user_bonus
  name: Trusted User Negative Score
  description: Reduce risk score for trusted users

  when:
    all:
      - event.user.verified == true
      - event.user.account_age_days > 365
      - event.user.dispute_count == 0

  score: -20

  metadata:
    category: trust_signals
    severity: low
    tags: [bonus, trusted]

# ----------------------------------------------------------------------------
# Ruleset 1: Transaction Monitoring
# ----------------------------------------------------------------------------

ruleset:
  id: transaction_monitoring_ruleset
  name: Transaction Monitoring
  description: Monitor transaction patterns and anomalies

  rules:
    - high_value_transaction
    - velocity_check
    - payment_method_check

  decision_logic:
    # High score threshold
    - condition: total_score >= 100
      action: review
      reason: "High transaction risk score"

    # Default
    - default: true
      action: approve
      reason: "Transaction monitoring passed"

  metadata:
    domain: transactions
    owner: risk_team

# ----------------------------------------------------------------------------
# Ruleset 2: User Behavior Analysis
# ----------------------------------------------------------------------------

ruleset:
  id: user_behavior_ruleset
  name: User Behavior Analysis
  description: Analyze user behavioral patterns

  rules:
    - suspicious_user_behavior
    - trusted_user_bonus

  decision_logic:
    # Suspicious behavior
    - condition: total_score >= 50
      action: review
      reason: "Suspicious user behavior detected"

    # Default
    - default: true
      action: approve
      reason: "User behavior normal"

  metadata:
    domain: user_behavior
    owner: fraud_team

# ----------------------------------------------------------------------------
# Ruleset 3: Fraud Detection
# ----------------------------------------------------------------------------

ruleset:
  id: fraud_detection_ruleset
  name: Fraud Detection
  description: Comprehensive fraud detection rules

  rules:
    - confirmed_fraud_pattern
    - complex_fraud_detection
    - risk_threshold_check

  decision_logic:
    # Critical fraud
    - condition: total_score >= 90
      action: deny
      reason: "Critical fraud risk detected"
      terminate: true

    # High fraud risk
    - condition: total_score >= 70
      action: review
      reason: "High fraud risk - requires review"

    # Default
    - default: true
      action: approve
      reason: "Fraud checks passed"

  metadata:
    domain: fraud
    owner: fraud_team

# ----------------------------------------------------------------------------
# PIPELINE: Comprehensive Risk Assessment
# ----------------------------------------------------------------------------

pipeline:
  id: comprehensive_risk_assessment
  name: Comprehensive Risk Assessment Pipeline
  description: |
    End-to-end risk assessment demonstrating core DSL features:
    - Conditional branching based on transaction amount
    - Multiple ruleset evaluation
    - Combined decision logic

  version: "1.0.0"

  # Entry point for the pipeline
  entry: blacklist_check

  # Execute for all test1 events
  when: event.type == "test1"

  steps:
    # Blacklist check step (directly deny and terminate if matched)
    - step:
        id: blacklist_check
        name: Blacklist Check
        type: router
        routes:
          - next: amount_router
            when:
              all:
                - user.ip_country not in list.high_risk_countries
        default: end

    # Router based on transaction amount
    - step:
        id: amount_router
        name: Transaction Amount Router
        type: router
        routes:
          # High/Medium-value transactions (>1000) - comprehensive check
          - next: transaction_monitoring_step
            when:
              all:
                - event.transaction.amount > 1000
        # Low-value transactions (<=1000) - basic check only
        default: basic_monitoring_step

    # Comprehensive check path (for amount > 1000)
    - step:
        id: transaction_monitoring_step
        name: Transaction Monitoring
        type: ruleset
        ruleset: transaction_monitoring_ruleset
        next: user_behavior_step

    - step:
        id: user_behavior_step
        name: User Behavior Analysis
        type: ruleset
        ruleset: user_behavior_ruleset
        next: fraud_detection_step

    - step:
        id: fraud_detection_step
        name: Fraud Detection
        type: ruleset
        ruleset: fraud_detection_ruleset
        next: end

    # Basic check path (for amount <= 1000)
    - step:
        id: basic_monitoring_step
        name: Basic Transaction Monitoring
        type: ruleset
        ruleset: transaction_monitoring_ruleset
        next: end
 

  # Pipeline metadata
  metadata:
    author: "Risk Engineering Team"
    version: "1.0.0"
    last_updated: "2025-12-14"
    features_demonstrated:
      - "Logical operators (any/all)"
      - "Comparison operators (>, <, ==, !=, >=, <=)"
      - "String operations (contains, in)"
      - "Arithmetic expressions"
      - "Nested conditions"
      - "Negative scoring"
      - "Ruleset composition"
      - "Conditional branching"
      - "Decision logic with multiple outcomes"
