version: "0.1"

# Production Fraud Detection Pipeline
# This pipeline uses the reusable fraud_detection_core ruleset from library

imports:
  rulesets:
    - library/rulesets/fraud_detection_core.yaml

---

pipeline:
  id: fraud_detection_pipeline
  name: Fraud Detection Pipeline
  description: Production-grade fraud detection for transaction events

  # Entry point for the pipeline
  entry: fraud_detection_step

  # Pipeline only executes for transaction events
  when:
    all:
      - event.type == "transaction"

  steps:
    # Execute the fraud detection ruleset
    - step:
        id: fraud_detection_step
        name: Fraud Detection Core
        type: ruleset
        ruleset: fraud_detection_core
        next: end
