version: "0.1"

# Production Fraud Detection Pipeline
# This pipeline uses the reusable fraud_detection_core ruleset from library

imports:
  rulesets:
    - library/rulesets/fraud_detection_core.yaml

---

pipeline:
  id: fraud_detection_pipeline
  name: Fraud Detection Pipeline
  description: Production-grade fraud detection for transaction events

  # Entry point for the pipeline
  entry: fraud_detection_step

  # Pipeline only executes for transaction events
  when:
    all:
      - event.type == "transaction"

  steps:
    # Execute the fraud detection ruleset
    - step:
        id: fraud_detection_step
        name: Fraud Detection Core
        type: ruleset
        ruleset: fraud_detection_core
        next: end

  metadata:
    # Required fields
    version: "1.0.0"
    author: "Fraud Prevention Team"
    updated: "2025-12-20 10:00:00"

    # Custom fields
    environment: "production"
    owner: "fraud_team"
