version: "0.1"

# Login Risk Assessment Pipeline
# Comprehensive login security pipeline with device trust, location analysis, and behavior monitoring

imports:
  rulesets:
    - library/rulesets/login_risk.yaml

---

pipeline:
  id: login_risk_pipeline
  name: Login Risk Assessment Pipeline
  description: |
    Production-grade login risk assessment pipeline.

    Flow:
    1. Event validation (only process login events)
    2. Execute login risk ruleset (5 security rules)
    3. Final decision based on risk score and patterns

    Covered Risk Dimensions:
    - Device Trust (emulators, spoofing, rooted devices)
    - Location Anomalies (impossible travel)
    - Account Takeover Patterns
    - Password Security
    - Failed Login Monitoring

  # Entry point for the pipeline
  entry: login_risk_check

  # Pipeline only executes for login-related events
  when: event.type == "login"

  steps:
    # ==========================================
    # Step 1: Execute Login Risk Ruleset
    # ==========================================
    - step:
        id: login_risk_check
        name: Login Risk Assessment
        type: ruleset
        ruleset: login_risk
        next: end

  metadata:
    # Required fields
    version: "1.0.0"
    author: "Security Team"
    updated: "2025-12-20 10:00:00"

    # Custom fields
    owner: "security_team"
    tags: [login, authentication, security]
