version: "0.1"

# Payment Risk Control Pipeline with Conditional Routing
# This pipeline uses reusable payment rulesets from library

imports:
  rulesets:
    - library/rulesets/payment_high_value.yaml
    - library/rulesets/payment_standard.yaml

---

pipeline:
  id: payment_risk_pipeline
  name: Payment Risk Control Pipeline
  description: Comprehensive payment risk assessment with conditional routing based on transaction amount

  # Entry point for the pipeline
  entry: ip_reputation_check

  # Pipeline only executes for payment events
  when:
    all:
      - event.type == "payment"

  steps:
    # Step 1: Check IP reputation via external API
    - step:
        id: ip_reputation_check
        name: IP Reputation Check
        type: api
        api: ipinfo
        endpoint: ip_lookup
        params:
          ip: ${event.ip_address}      # Expression: read from event data
          token: "a63066c9a63590"       # Literal: API token
        next: amount_router

    # Step 2: Router based on payment amount
    - step:
        id: amount_router
        name: Payment Amount Router
        type: router
        routes:
          # High-value transactions (> $1000)
          - next: high_value_check
            when:
              all:
                - payment_amount > 1000
          # Standard transactions (<= $1000)
          - next: standard_check
            when:
              all:
                - payment_amount <= 1000
        default: standard_check

    # Step 3a: High-value payment check
    - step:
        id: high_value_check
        name: High Value Payment Assessment
        type: ruleset
        ruleset: payment_high_value
        next: end

    # Step 3b: Standard payment check
    - step:
        id: standard_check
        name: Standard Payment Assessment
        type: ruleset
        ruleset: payment_standard
        next: end

  metadata:
    # Required fields
    version: "1.0.0"
    author: "Payment Security Team"
    updated: "2025-12-20 10:00:00"

    # Custom fields
    environment: "production"
    owner: "payment_team"
