version: "0.1"

# Supabase Feature-Based Risk Control Ruleset
# This ruleset demonstrates how to use calculated features in rule conditions

# ========================================
# STAGE 0: PIPELINE DEFINITION
# ========================================
# Pipeline is the entry point with mandatory when condition

pipeline:
  id: supabase_transaction_pipeline
  name: Supabase Transaction Risk Pipeline
  description: Transaction risk assessment using features calculated from Supabase PostgreSQL database

  # Entry point for the pipeline
  entry: supabase_risk_step

  # Mandatory when condition - only process transaction events with source="supabase"
  when:
    all:
      - event.type == "transaction"
      - event.source == "supabase" 

  steps:
    # Execute the transaction risk assessment ruleset
    - step:
        id: supabase_risk_step
        name: Supabase Risk Assessment
        type: ruleset
        ruleset: supabase_risk_assessment
        # No next = end steps, flow to decision

  # Final decision based on signals from rulesets
  # Since ruleset now produces standard signals, pipeline just passes them through
  decision:
    # Decline signal → decline result
    - when: results.supabase_risk_assessment.signal == "decline"
      result: decline
      reason: "{results.supabase_risk_assessment.reason}"

    # Hold signal → hold result
    - when: results.supabase_risk_assessment.signal == "hold"
      result: hold
      actions: ["2FA"]
      reason: "{results.supabase_risk_assessment.reason}"

    # Review signal → review result
    - when: results.supabase_risk_assessment.signal == "review"
      result: review
      actions: ["KYC","2FA"]
      reason: "{results.supabase_risk_assessment.reason}"

    # Approve (default)
    - default: true
      result: approve
      reason: "Transaction approved"

---

# ========================================
# STAGE 1: RISK DETECTION RULES
# ========================================
# Rules that reference features calculated from Supabase data

# Rule 1: High Transaction Volume Detection
rule:
  id: high_transaction_volume
  name: High Transaction Volume
  description: Detect users with unusually high transaction volume in 7 days
  
  # No need to repeat event.type here - guaranteed by pipeline
  when:
    all:
      - features.transaction_sum_7d > 5000
      - features.transaction_count_24h > 10
  
  score: 50

---

# Rule 2: High-Value Transaction Pattern
rule:
  id: high_value_transaction
  name: High-Value Transaction Pattern
  description: Large transaction amount detected

  when:
    all:
      - event.amount >= 500

  score: 35

---

# Rule 3: Rapid Transaction Frequency
rule:
  id: rapid_transactions
  name: Rapid Transaction Frequency
  description: Too many transactions in short time window

  when:
    all:
      - features.transaction_count_24h > 20

  score: 45

---

# Rule 4: Suspicious Device Pattern
rule:
  id: suspicious_device_pattern
  name: Suspicious Device Pattern
  description: User accessing from multiple devices with high transaction volume

  when:
    all:
      - features.device_event_count_3mo >= 2
      - features.device_transaction_count_6mo >= 4

  score: 60

---

# ========================================
# STAGE 2: SIGNAL PRODUCTION RULESET
# ========================================
# Ruleset produces signals (risk levels), pipeline makes final decisions

ruleset:
  id: supabase_risk_assessment
  name: Supabase Transaction Risk Assessment
  description: |
    Risk assessment ruleset that uses features calculated from Supabase PostgreSQL database.
    Features are computed in real-time from event data stored in Supabase.
    This ruleset produces signals, which are consumed by the pipeline's decision section.

  rules:
    - high_transaction_volume
    - high_value_transaction
    - rapid_transactions
    - suspicious_device_pattern

  # Conclusion produces signals (initial decision: approve/decline/review/hold/pass)
  conclusion:
    # Critical risk - decline immediately
    - when: triggered_rules contains "suspicious_device_pattern2"
      signal: decline
      reason: "Suspicious device pattern with high transaction volume detected"

    # High risk - decline
    - when: total_score >= 100
      signal: decline
      reason: "High risk score threshold exceeded"

    # High risk - multiple indicators
    - when: triggered_count >= 3
      signal: decline
      reason: "Multiple risk indicators detected"

    # Medium risk - hold for verification
    - when: total_score >= 80
      signal: hold
      reason: "Medium-high risk score"

    # Low risk - review
    - when: total_score >= 35
      signal: review
      reason: "Low risk score"

    # Normal - approve (default)
    - default: true
      signal: approve
      reason: "No significant risk indicators"

