// This file is @generated by prost-build.
/// Request for making a decision
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecideRequest {
    /// Event data (required) - key-value pairs
    #[prost(map = "string, message", tag = "1")]
    pub event: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
    /// User profile/context (optional)
    #[prost(map = "string, message", tag = "2")]
    pub user: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
    /// Feature computation results (optional)
    #[prost(map = "string, message", tag = "3")]
    pub features: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
    /// Request options (optional)
    #[prost(message, optional, tag = "4")]
    pub options: ::core::option::Option<RequestOptions>,
    /// Request metadata (optional)
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Request options
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestOptions {
    /// Score normalization strategy
    #[prost(string, optional, tag = "1")]
    pub score_normalization: ::core::option::Option<::prost::alloc::string::String>,
    /// Pipeline ID to execute (optional, if not specified, will be determined by registry)
    #[prost(string, optional, tag = "2")]
    pub pipeline_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether to include detailed trace information
    #[prost(bool, tag = "3")]
    pub include_trace: bool,
    /// Whether to include feature values in response
    #[prost(bool, tag = "4")]
    pub include_features: bool,
}
/// Response from decision
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecideResponse {
    /// Unique request ID
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// HTTP status code
    #[prost(int32, tag = "2")]
    pub status: i32,
    /// Processing time in milliseconds
    #[prost(int64, tag = "3")]
    pub process_time_ms: i64,
    /// Pipeline ID that was executed
    #[prost(string, tag = "4")]
    pub pipeline_id: ::prost::alloc::string::String,
    /// Decision result
    #[prost(message, optional, tag = "5")]
    pub decision: ::core::option::Option<Decision>,
    /// Error message if any
    #[prost(string, optional, tag = "6")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    /// Execution trace (if requested)
    #[prost(message, optional, tag = "7")]
    pub trace: ::core::option::Option<ExecutionTrace>,
    /// Feature values (if requested)
    #[prost(map = "string, message", tag = "8")]
    pub features: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
/// Decision result
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Decision {
    /// Decision result (APPROVE, DECLINE, REVIEW, CHALLENGE)
    #[prost(string, tag = "1")]
    pub result: ::prost::alloc::string::String,
    /// Actions to take
    #[prost(message, repeated, tag = "2")]
    pub actions: ::prost::alloc::vec::Vec<Action>,
    /// Risk scores
    #[prost(message, optional, tag = "3")]
    pub scores: ::core::option::Option<Scores>,
    /// Evidence for the decision
    #[prost(message, optional, tag = "4")]
    pub evidence: ::core::option::Option<Evidence>,
    /// Human-readable explanation
    #[prost(message, optional, tag = "5")]
    pub cognition: ::core::option::Option<Cognition>,
}
/// Action to take
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Action {
    /// Action type (block_user, send_notification, etc.)
    #[prost(string, tag = "1")]
    pub action_type: ::prost::alloc::string::String,
    /// Action parameters
    #[prost(map = "string, message", tag = "2")]
    pub params: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
/// Risk scores
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Scores {
    /// Canonical score (normalized)
    #[prost(double, tag = "1")]
    pub canonical: f64,
    /// Raw score (before normalization)
    #[prost(double, tag = "2")]
    pub raw: f64,
}
/// Evidence for the decision
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Evidence {
    /// Triggered rules
    #[prost(string, repeated, tag = "1")]
    pub triggered_rules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Additional evidence data
    #[prost(map = "string, message", tag = "2")]
    pub data: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
/// Human-readable explanation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cognition {
    /// Summary of the decision
    #[prost(string, tag = "1")]
    pub summary: ::prost::alloc::string::String,
    /// Reason codes
    #[prost(string, repeated, tag = "2")]
    pub reason_codes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Additional cognition data
    #[prost(map = "string, message", tag = "3")]
    pub data: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
/// Execution trace
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionTrace {
    /// Pipeline trace
    #[prost(message, optional, tag = "1")]
    pub pipeline: ::core::option::Option<PipelineTrace>,
    /// Step traces
    #[prost(message, repeated, tag = "2")]
    pub steps: ::prost::alloc::vec::Vec<StepTrace>,
}
/// Pipeline trace
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PipelineTrace {
    /// Pipeline ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Pipeline name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Execution status
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
}
/// Step trace
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StepTrace {
    /// Step ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Step type
    #[prost(string, tag = "2")]
    pub step_type: ::prost::alloc::string::String,
    /// Execution status
    #[prost(string, tag = "3")]
    pub status: ::prost::alloc::string::String,
    /// Step result
    #[prost(map = "string, message", tag = "4")]
    pub result: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
/// Generic value type (similar to JSON value)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    #[prost(oneof = "value::Kind", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub kind: ::core::option::Option<value::Kind>,
}
/// Nested message and enum types in `Value`.
pub mod value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(bool, tag = "1")]
        BoolValue(bool),
        #[prost(int64, tag = "2")]
        IntValue(i64),
        #[prost(double, tag = "3")]
        DoubleValue(f64),
        #[prost(string, tag = "4")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag = "5")]
        ListValue(super::ListValue),
        #[prost(message, tag = "6")]
        MapValue(super::MapValue),
        #[prost(enumeration = "super::NullValue", tag = "7")]
        NullValue(i32),
    }
}
/// List value
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListValue {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<Value>,
}
/// Map value
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapValue {
    #[prost(map = "string, message", tag = "1")]
    pub fields: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
}
/// Health check request
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {}
/// Health check response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    /// Health status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// Server version
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
/// Reload repository request
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReloadRepositoryRequest {}
/// Reload repository response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReloadRepositoryResponse {
    /// Success status
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Number of pipelines loaded
    #[prost(int32, tag = "3")]
    pub pipelines_loaded: i32,
    /// Number of rules loaded
    #[prost(int32, tag = "4")]
    pub rules_loaded: i32,
}
/// Null value
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NullValue {
    NullValue = 0,
}
impl NullValue {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NullValue => "NULL_VALUE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NULL_VALUE" => Some(Self::NullValue),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod decision_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with DecisionServiceServer.
    #[async_trait]
    pub trait DecisionService: std::marker::Send + std::marker::Sync + 'static {
        /// Make a decision based on event data
        async fn decide(
            &self,
            request: tonic::Request<super::DecideRequest>,
        ) -> std::result::Result<tonic::Response<super::DecideResponse>, tonic::Status>;
        /// Health check
        async fn health_check(
            &self,
            request: tonic::Request<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        >;
        /// Reload repository (pipelines, rules, features)
        async fn reload_repository(
            &self,
            request: tonic::Request<super::ReloadRepositoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReloadRepositoryResponse>,
            tonic::Status,
        >;
    }
    /// Decision service for risk assessment and fraud detection
    #[derive(Debug)]
    pub struct DecisionServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> DecisionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for DecisionServiceServer<T>
    where
        T: DecisionService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/corint.decision.v1.DecisionService/Decide" => {
                    #[allow(non_camel_case_types)]
                    struct DecideSvc<T: DecisionService>(pub Arc<T>);
                    impl<
                        T: DecisionService,
                    > tonic::server::UnaryService<super::DecideRequest>
                    for DecideSvc<T> {
                        type Response = super::DecideResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DecideRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DecisionService>::decide(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DecideSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/corint.decision.v1.DecisionService/HealthCheck" => {
                    #[allow(non_camel_case_types)]
                    struct HealthCheckSvc<T: DecisionService>(pub Arc<T>);
                    impl<
                        T: DecisionService,
                    > tonic::server::UnaryService<super::HealthCheckRequest>
                    for HealthCheckSvc<T> {
                        type Response = super::HealthCheckResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthCheckRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DecisionService>::health_check(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthCheckSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/corint.decision.v1.DecisionService/ReloadRepository" => {
                    #[allow(non_camel_case_types)]
                    struct ReloadRepositorySvc<T: DecisionService>(pub Arc<T>);
                    impl<
                        T: DecisionService,
                    > tonic::server::UnaryService<super::ReloadRepositoryRequest>
                    for ReloadRepositorySvc<T> {
                        type Response = super::ReloadRepositoryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReloadRepositoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DecisionService>::reload_repository(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReloadRepositorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for DecisionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "corint.decision.v1.DecisionService";
    impl<T> tonic::server::NamedService for DecisionServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
